### ISSUE TITLE
empty? invoked on nil

### ISSUE THREAD

**Issue by bootstraponline** [bootstraponline/rspec_junit#2]
```
/Users/user/.rvm/gems/ruby-2.2.2/gems/rspec-core-3.3.2/lib/rspec/core/backtrace_formatter.rb:34:in `format_backtrace': undefined method `empty?' for nil:NilClass (NoMethodError)
    from /Users/user/.rvm/gems/ruby-2.2.2/gems/rspec_junit-3.0.0/lib/rspec_junit/junit.rb:38:in `failure_details_for'
    from /Users/user/.rvm/gems/ruby-2.2.2/gems/rspec_junit-3.0.0/lib/rspec_junit/junit.rb:115:in `block in build_failed_test'
    from /Users/user/.rvm/gems/ruby-2.2.2/gems/builder-3.2.2/lib/builder/xmlbase.rb:175:in `call'
    from /Users/user/.rvm/gems/ruby-2.2.2/gems/builder-3.2.2/lib/builder/xmlbase.rb:175:in `_nested_structures'
    from /Users/user/.rvm/gems/ruby-2.2.2/gems/builder-3.2.2/lib/builder/xmlbase.rb:68:in `tag!'
    from /Users/user/.rvm/gems/ruby-2.2.2/gems/builder-3.2.2/lib/builder/xmlbase.rb:93:in `method_missing'
    from /Users/user/.rvm/gems/ruby-2.2.2/gems/rspec_junit-3.0.0/lib/rspec_junit/junit.rb:114:in `build_failed_test'
    from /Users/user/.rvm/gems/ruby-2.2.2/gems/rspec_junit-3.0.0/lib/rspec_junit/junit.rb:106:in `block in build_test'
    from /Users/user/.rvm/gems/ruby-2.2.2/gems/builder-3.2.2/lib/builder/xmlbase.rb:175:in `call'
    from /Users/user/.rvm/gems/ruby-2.2.2/gems/builder-3.2.2/lib/builder/xmlbase.rb:175:in `_nested_structures'
    from /Users/user/.rvm/gems/ruby-2.2.2/gems/builder-3.2.2/lib/builder/xmlbase.rb:68:in `tag!'
    from /Users/user/.rvm/gems/ruby-2.2.2/gems/builder-3.2.2/lib/builder/xmlbase.rb:93:in `method_missing'
    from /Users/user/.rvm/gems/ruby-2.2.2/gems/rspec_junit-3.0.0/lib/rspec_junit/junit.rb:101:in `build_test'
    from /Users/user/.rvm/gems/ruby-2.2.2/gems/rspec_junit-3.0.0/lib/rspec_junit/junit.rb:91:in `block in build_all_tests'
    from /Users/user/.rvm/gems/ruby-2.2.2/gems/rspec_junit-3.0.0/lib/rspec_junit/junit.rb:90:in `each'
    from /Users/user/.rvm/gems/ruby-2.2.2/gems/rspec_junit-3.0.0/lib/rspec_junit/junit.rb:90:in `build_all_tests'
    from /Users/user/.rvm/gems/ruby-2.2.2/gems/rspec_junit-3.0.0/lib/rspec_junit/junit.rb:85:in `block in build_test_suite'
    from /Users/user/.rvm/gems/ruby-2.2.2/gems/builder-3.2.2/lib/builder/xmlbase.rb:175:in `call'
    from /Users/user/.rvm/gems/ruby-2.2.2/gems/builder-3.2.2/lib/builder/xmlbase.rb:175:in `_nested_structures'
    from /Users/user/.rvm/gems/ruby-2.2.2/gems/builder-3.2.2/lib/builder/xmlbase.rb:68:in `tag!'
    from /Users/user/.rvm/gems/ruby-2.2.2/gems/builder-3.2.2/lib/builder/xmlbase.rb:93:in `method_missing'
    from /Users/user/.rvm/gems/ruby-2.2.2/gems/rspec_junit-3.0.0/lib/rspec_junit/junit.rb:77:in `build_test_suite'
    from /Users/user/.rvm/gems/ruby-2.2.2/gems/rspec_junit-3.0.0/lib/rspec_junit/junit.rb:69:in `block in build_all_suites'
    from /Users/user/.rvm/gems/ruby-2.2.2/gems/rspec_junit-3.0.0/lib/rspec_junit/junit.rb:68:in `each'
    from /Users/user/.rvm/gems/ruby-2.2.2/gems/rspec_junit-3.0.0/lib/rspec_junit/junit.rb:68:in `build_all_suites'
    from /Users/user/.rvm/gems/ruby-2.2.2/gems/rspec_junit-3.0.0/lib/rspec_junit/junit.rb:63:in `block in build_results'
    from /Users/user/.rvm/gems/ruby-2.2.2/gems/builder-3.2.2/lib/builder/xmlbase.rb:175:in `call'
    from /Users/user/.rvm/gems/ruby-2.2.2/gems/builder-3.2.2/lib/builder/xmlbase.rb:175:in `_nested_structures'
    from /Users/user/.rvm/gems/ruby-2.2.2/gems/builder-3.2.2/lib/builder/xmlbase.rb:68:in `tag!'
    from /Users/user/.rvm/gems/ruby-2.2.2/gems/builder-3.2.2/lib/builder/xmlbase.rb:93:in `method_missing'
    from /Users/user/.rvm/gems/ruby-2.2.2/gems/rspec_junit-3.0.0/lib/rspec_junit/junit.rb:56:in `build_results'
    from /Users/user/.rvm/gems/ruby-2.2.2/gems/rspec_junit-3.0.0/lib/rspec_junit/junit.rb:24:in `dump_summary'
    from /Users/user/.rvm/gems/ruby-2.2.2/gems/rspec-core-3.3.2/lib/rspec/core/reporter.rb:184:in `block in notify'
    from /Users/user/.rvm/gems/ruby-2.2.2/gems/rspec-core-3.3.2/lib/rspec/core/reporter.rb:183:in `each'
    from /Users/user/.rvm/gems/ruby-2.2.2/gems/rspec-core-3.3.2/lib/rspec/core/reporter.rb:183:in `notify'
    from /Users/user/.rvm/gems/ruby-2.2.2/gems/rspec-core-3.3.2/lib/rspec/core/reporter.rb:162:in `block in finish'
    from /Users/user/.rvm/gems/ruby-2.2.2/gems/rspec-core-3.3.2/lib/rspec/core/reporter.rb:170:in `close_after'
    from /Users/user/.rvm/gems/ruby-2.2.2/gems/rspec-core-3.3.2/lib/rspec/core/reporter.rb:151:in `finish'
    from /Users/user/.rvm/gems/ruby-2.2.2/gems/rspec-core-3.3.2/lib/rspec/core/reporter.rb:79:in `report'
    from /Users/user/.rvm/gems/ruby-2.2.2/gems/rspec-core-3.3.2/lib/rspec/core/runner.rb:113:in `run_specs'
    from /Users/user/.rvm/gems/ruby-2.2.2/gems/rspec-core-3.3.2/lib/rspec/core/runner.rb:89:in `run'
    from /Users/user/.rvm/gems/ruby-2.2.2/gems/rspec-core-3.3.2/lib/rspec/core/runner.rb:73:in `run'
    from /Users/user/.rvm/gems/ruby-2.2.2/gems/rspec-core-3.3.2/lib/rspec/core/runner.rb:41:in `invoke'
    from /Users/user/.rvm/gems/ruby-2.2.2/gems/rspec-core-3.3.2/exe/rspec:4:in `<top (required)>'
    from /Users/user/.rvm/gems/ruby-2.2.2/bin/rspec:23:in `load'
    from /Users/user/.rvm/gems/ruby-2.2.2/bin/rspec:23:in `<main>'
    from /Users/user/.rvm/gems/ruby-2.2.2/bin/ruby_executable_hooks:15:in `eval'
    from /Users/user/.rvm/gems/ruby-2.2.2/bin/ruby_executable_hooks:15:in `<main>'
```

**Comment by bootstraponline** [comment]
`exception.backtrace` may be nil in junit.rb
